build:
  image: ubuntu:14.04
  commands:
    - sudo apt update && sudo apt install -y git-core
    # Do an initial checkout to allow the Dockerfile prime the image with gradle and dependencies
    # For now, clone a specific branch
    - git clone --depth=5 https://github.com/reddit/Frontpage-Android.git Frontpage-Android

# Pushes to master branch result in an image being built and pushed to
# Docker Hub as reddit/reddit-android-build:latest.
publish:
  docker:
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: android@reddit.com
    repo: reddit/reddit-android-build
    registry: quay.io
    tag: latest
    file: Dockerfile
    when:
      branch: master

# These plugins are triggered after a build failure/success.
notify:
  slack:
    webhook_url: $$CI_SLACK_WEBHOOK_URL
    channel: ci-notifications
